version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "venus/beeple"
    network_mode: "host"
  venus-mysql:
    image: mysql:latest
    network_mode: "host"
    environment:
      - MYSQL_USER=venus
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=jdbc:mysql://seng426-team3-mysql.mysql.database.azure.com:3306/venus
